format = """
$sudo\
$os\
$hostname\
$shell\
$shlvl\
$jobs\
$directory\
$aws\
$git_branch\
$git_status\
$git_metrics\
$nodejs\
$python\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$scala\
$haskell\
$lua\
$docker_context\
$cmd_duration\
$time\
\n$character"""

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[palettes.tokyonight]
color_fg0 = '#769ff0'
color_fg1 = '#83a598'
color_bg3 = '#665c54'
color_blue = '#212736'

[sudo]
disabled = false
style = "bg:#e84a96"
format = '[ $symbol]($style)[î‚´](fg:#e84a96 bg:#a3aed2)'

[os]
disabled = false
style = "bold fg:#090c0c bg:#a3aed2"
format = "[î‚´](fg:prev_bg bg:#a3aed2)[$symbol]($style)"

[hostname]
ssh_only = false
style = "fg:#090c0c bg:#a3aed2"
format = "[î‚´](fg:prev_bg bg:prev_bg)[$hostname ]($style)"

[shell]
disabled = false
bash_indicator = 'bash'
fish_indicator = 'ó°ˆº '
powershell_indicator = 'ï‘ _'
unknown_indicator = 'mystery shell'
style = 'fg:#090c0c bg:#61687e'
format = "[î‚´](fg:prev_bg bg:#61687e)[ $indicator]($style)"

[shlvl]
disabled = false
symbol = 'â¯'
repeat = true
threshold = 1
style = 'fg:#090c0c bg:#61687e'
format = "[ $symbol]($style)"

[jobs]
symbol = '+'
number_threshold = 1
symbol_threshold = 1
style = 'fg:#090c0c bg:#61687e'
format = "[$symbol$number]($style)"

[directory]
style = "fg:#e3e5e5 bg:#487feb"
format = "[î‚´](fg:prev_bg bg:#61687e)[î‚´](fg:prev_bg bg:#487feb)[ $path ]($style)"
truncation_length = 1

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[aws]
disabled = false
force_display = false
style = 'fg:#000000 bg:#e2b75e'
symbol = 'aws'
format = '[[î‚´](fg:prev_bg bg:#e2b75e) $symbol: ($profile )(\($region\) )]($style)'

[git_branch]
symbol = "ï˜"
style = "fg:#769ff0 bg:#394260"
format = '[[î‚´](fg:prev_bg bg:#394260) $symbol $branch ]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[git_metrics]
disabled = false
added_style = "fg:green bg:prev_bg"
deleted_style = "fg:red bg:prev_bg"
format = '([+$added ]($added_style)[-$deleted ]($deleted_style))'

[nodejs]
symbol = "îœ˜"
style = "fg:green bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[python]
symbol = "î˜†"
style = "fg:green bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[c]
symbol = "î˜ "
style = "fg:#767676 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[rust]
symbol = "î¨"
style = "fg:#dea584 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[golang]
symbol = "î˜§"
style = "fg:#00add8 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[php]
symbol = "î˜ˆ"
style = "fg:#8892be bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[java]
symbol = "î‰– "
style = "fg:#b07219 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[kotlin]
symbol = "î˜´"
style = "fg:#a97bff bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[scala]
symbol = 'ğŸŒŸ'
style = "fg:red bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "fg:#9a5f96 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[lua]
symbol = "ğŸŒ™"
detect_folders = ['lua']
style = "fg:#6666b2 bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[swift]
symbol = "ğŸ¦"
style = "fg:#fe4d2b bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[zig]
symbol = "â†¯"
style = "fg:#e7953a bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:blue bg:#212736"
format = '[[î‚´](fg:prev_bg bg:#212736) $symbol ($version )]($style)'

[cmd_duration]
# Always display command duration.
min_time = 0
style = "fg:yellow bg:#1d2230"
format = "[[î‚´](fg:prev_bg bg:#1d2230) \ueba2 $duration]($style)"
show_milliseconds = true

[time]
disabled = false
time_format = "%R" # Format: HH:mm
style = "fg:#a0a9cb bg:#1d2230"
format = '[î‚´](fg:prev_bg bg:#1d2230)[ ïº $time ]($style)[î‚´](fg:#1d2230)'
